[theme]
# اگر می‌خواهی تم روشن باشد مقدار را "light" بگذار
base = "dark"
primaryColor = "#4BA3F5"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"
font = "sans serif"
